### ISSUE TITLE
read credential info (e.g. cookie) from a file instead of hardcoded in the config file

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/iobox-win32#1]
This will enable us to commit the config file in git without exposing credential information. 
We can use credential_file that point to a file name in the main config file instead. 

The cookie file is expected to contain a json object e.g. 

```
{
  "username" : "xxx"
  "password" : "xxx"
  "cookie" : "xxx"
}
```

**Comment by svoinea** [comment]
Done in the commit cf341289dd75733e2adb9e093e7ea67139db2558. The README file was updated accordantly. Assigning @akumar03 for review.
