### ISSUE TITLE
setup.py should be in base dir

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/iobox-win32#10]
not in `src/service`

**Comment by svoinea** [comment]
The `src/service/setup.py` file is used only on the Windows environment to generate the executable used by the Windows service. It is run as:
`python setup.py py2exe`.
Therefore, it is not an usual Python installation that uses the `install` option.
Meanwhile, a Linux version was developed, and that one uses a Python installation having a `setup.py` file in the base directory.

**Comment by robes** [comment]
@svoinea That works for me... however, we probably should not call this the `iobox-win32` anymore if it is now a Linux version.
