### ISSUE TITLE
Present informative error messages in the log files

### ISSUE THREAD

**Issue by akumar03** [informatics-isi-edu/iobox-win32#12]
The log file generated by iobox is helpful in debugging issues. Providing informative log messages can save  significant time while configuring and debugging the system. Here is a list of few errors:
1. If the configuration json file is not parsable then error should be reported
2. URL should be complete, instead of  url="/hatrac/assets/USC/fcs/2016", adding the server name would help
3. Fill in the error value instead of leaving it empty Exception: Can not retrieve namespace "/hatrac/assets/USC/fcs/2016". Error: ""

**Comment by svoinea** [comment]
Item 1 was already fixed in issue #13.

**Comment by hongsudt** [comment]
@svoinea have you addressed bullet 2 and 3?

**Comment by svoinea** [comment]
Point 2 was addressed in the commit b4cc261b5cdf3b8506fda4d19e6a9577735470ee
Point 3 passes the error messages as received from the server.

**Comment by svoinea** [comment]
Assigning for review to @akumar03
