### ISSUE TITLE
Support hierarchy in monitored input directory

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/iobox-win32#15]
This is a set of behaviors we should consider if we are going to support detection and processing of hierarchical content within a monitored input directory, rather than just a flat set of independent input files. There are a lot of pieces to this and we should discuss and analyze before starting any work.
- [x] Allow the regular expression pattern to process the hierarchical name, not just the basename of the file.
  - [x] Support `basename_pattern` to only process basename, e.g. `myimage.tiff` (alias to `pattern` for backward compatibilty?)
  - [x] Support `relpath_pattern` to process the relative name beyond the monitored input directory, e.g. `a/b/myimage.tiff`
  - [ ] Support `fullpath_pattern` to process the full name including the monitored input path, e.g. `/some/path/input/a/b/myimage.tiff`
- [x] Recreate the relative hierarchy and move the processed file into its same relative path structure under the complete or rejected output directories.
- [x] Some option to prune empty input sub-directories?  Would need timestamp-based heuristics so that it is safe/easy to create a new input directory and add content to it without a race condition. But, as files are processed and transferred, you probably want to clear input sub-directories that are no longer being used...
- [ ] Some option to process groups of files together?
  - [ ] Guard conditions to delay a processing rule until some other condition is met besides input file match
  - [ ] Some way to sequence the set of rules grouped by a guard condition match
  - [ ] Some way to share environment of metadata discovery between files in a group, i.e. allow metadata extracted from one processed file to be consumed while processing subsequent files. Useful for metadata files etc.

**Comment by karlcz** [comment]
@svoinea I've noticed you made some commits related to this, so wanted to make sure you've seen this issue... these aren't scheduled tasks but it would be good to keep in mind an overall goal if working on patches related to any of these topics...

**Comment by karlcz** [comment]
@svoinea @hongsudt I think a bunch of the items in this old issue have been addressed but in slightly different ways.  Please revise the issue description's checklist to reflect changes in approach and also current progress/status as I think some features now exist?

**Comment by hongsudt** [comment]
@svoinea can you please update the status of this issue? If all of them are done, we should close it.

**Comment by svoinea** [comment]
For relative name matching, the `relpath_matching` rule was created: if present and equal to `true`, the pattern will be applied to the relative path of the file. By default, the pattern is applied to the basename of the file.
For pruning empty input sub-directories, the `dir_cleanup_patterns` rule was created: if present, it contains an array of patterns. Empty subdirectories of the `inbox` will be deleted only if their relative path matches any of the patterns of `dir_cleanup_patterns`. By default, all the empty subdirectories of the `inbox` will be deleted.

**Comment by karlcz** [comment]
I think the checkboxes reflect the current status and it seems to support existing use case goals so we should just close this.
