### ISSUE TITLE
Preserve the tree structure on the output directory

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/iobox-win32#16]
The watcher detects also new files from the subdirectories.
The output directory should keep that tree structure.

**Comment by svoinea** [comment]
Done through the commit 676bbdb99fd5453918077817c291b85e719da22a

In the input directory, the subdirectories will be removed if they don't contain any more files.

**Comment by karlcz** [comment]
> In the input directory, the subdirectories will be removed if they
> don't contain any more files.

This needs to have a substantial delay, i.e. hours or days since the
directory last changed before deleting it.

Otherwise you will have aggravating race conditions with whatever
process is trying to create input directories and place files there.

**Comment by hongsudt** [comment]
@karlcz can we close this issue since we now explicitly tell the config which directory can be deleted?

**Comment by karlcz** [comment]
yes I think so.
