### ISSUE TITLE
The hatrac_location substitution includes an erroneous trailing new-line character

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/iobox-win32#24]
In an iobox ruleset I send some data to ermrest such as:

```
  {
     "handler": "ermrest",
     "method": "POST",
     "warn_on_duplicates": true,
     "colmap": {
        "Subject": "%(Subject)s",
        "URL": "%(hatrac_location)s"
     },
     "webconn": "example1",
     "url": "https://example1.com/ermrest/catalog/1/entity/MySchema:MyTable"
 }
```

The actual value stored to the "URL" column includes a newline character at the end of the hatrac URL when it should not.  E.g. the JSON result from ERMrest to return one of these rows looks like:

`{"Subject": "example", "URL":"/hatrac/examplefile:E2JFEK6LFEGLCSAXN34IRX1234\n"}`

Where that final `\n` should not be there.

**Comment by hongsudt** [comment]
@svoinea please update the issue.

**Comment by svoinea** [comment]
Done in commit 89bf0a93a9c036a173f35e4f09ad0e6ffac08079.
Assigning to @karlcz for review.

**Comment by karlcz** [comment]
I can confirm that this worked as intended in our redeployed iobox.
