### ISSUE TITLE
turn on relative path maching mode to allow pattern matching on file path

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/iobox-win32#26]
There is a usecase that instead of deposit a file into the iobox, they want to deposit a folder e.g. a folder named GPCRUSC20160917EXP1.aia which contains signal1.cdf, signal2.cdf. The iobox should expose the file path metadata, so that the regular expression can be done to the path instead of just the base filename.   

A new configuration option `relpath_matching` within each rule block should accept a boolean value:
- true: construct a target filename from the whole relative path and basename (everything below the inbox folder level)
- false: construct a target filename from just the basename (default if option is not configured for backwards-compatibility)

The same regexp pattern field in the current rule syntax will then be matched against this potentially longer string.

I think we **should** form the target name using `/` (forward slash) regardless of platform. It will be very painful to have to use `\` (back slash) in Python regular expressions embedded in JSON config files and get the right level of escaping for the intended path matches.

**Comment by svoinea** [comment]
Implemented through the commit c7ba4aa1313cdbf2c19e191ea5452a346af31b61

**Comment by akumar03** [comment]
Tested and created a release: https://github.com/informatics-isi-edu/iobox-win32/tree/gpcr-20160914.1
