### ISSUE TITLE
support directory clean up pattern handler

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/iobox-win32#27]
IObox should allow an array of dir clean-up pattern e.g. 
`dir_cleanup_patterns": ["fcs/.*", "sdspage/[^/]+/.*", "sec/[^/]+/.*"]`

The default should be `dir_cleanup_patterns":[".*"]` which is to clean up everything.

**Comment by svoinea** [comment]
Implemented through the commit c7ba4aa1313cdbf2c19e191ea5452a346af31b61

**Comment by akumar03** [comment]
tested and created a tag for gpcr: https://github.com/informatics-isi-edu/iobox-win32/tree/gpcr-20160914.1
