### ISSUE TITLE
Make codebase portable for Linux deployments

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/iobox-win32#28]
1. Use runtime detection to decide whether windows-specific modules can be imported
2. Fall back to portable file enumeration via polling when not using windows-specific file change monitoring
3. Isolate any use of windows-specific exception classes and similar so that all code paths work in absence of windows-specific modules where those classes are defined
4. Make sure `python setup.py install` will work on Linux
5. Just assume the iobox daemon process will be started manually as the correct user.
6. Accept configuration file location as a command-line argument to avoid platform-specific assumptions about where to find the file?

**Comment by svoinea** [comment]
A Linux version was implemented. The `README` file was updated with the `IObox Linux System Requirements` and `IObox Linux Installation` sections. Briefly, you need to:
- install the `scandir` prerequisite by running:
  
   `pip install scandir`
- install the agent by running:
  
   `python setup.py install`
- start the agent by running:
  
   `iobox-agent -c <configuration_file>`

**Comment by karlcz** [comment]
I confirmed that this works on a Fedora 24 workstation.  I used the `python2-scandir` package from the Fedora repository instead of installing the preequisite with `pip`.
