### ISSUE TITLE
When hatrac object already exists, hatrac_location is not set in environment

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/iobox-win32#29]
I have a ruleset like:

```
...
{
  "handler": "hatrac",
  "warn_on_duplicates": true,
  "webconn": "myconnection",
  "url": "https://example.org/hatrac/example.txt",
  "create_parents": true,
  "failure": "transfer"
}
{
  "handler": "ermrest",
  "method": "PUT",
  "colmap": {
    "ID": "%(ID)s",
    "URL": "%(hatrac_location)s"
  },
  "webconn": "myconnection",
  "url": "https://example.org/ermrest/catalog/1/attributegroup/Table/ID;URL"
}
...
```

On regular uploads, it works and sets the URL column to the new hatrac URL obtained by the hatrac object PUT request.

On a duplicate, it finds the existing object version, warns that it is skipping upload, but fails to set the `hatrac_location` in the environment.  The ermrest table gets updated with the literal value `%(hatrac_location)s` in the URL column instead of the existing object-version URL.

**Comment by svoinea** [comment]
The bug was fixed through the commit c81845cb8e40355953fe1241eb27a2ab35f7bde7

**Comment by karlcz** [comment]
The URL it supplies when upload is skipped is missing the "/hatrac" prefix

Edit: I said "/hatrac/" but changed it to "/hatrac" as the URL does start with a "/" already

**Comment by karlcz** [comment]
OK, so this was a bug in Hatrac and once it is updated to return proper URLs in a version enumeration request, the iobox-agent is now sending them as well.
