### ISSUE TITLE
On creation, if an entry already exist in ermrest, provide an option to automatically update

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/iobox-win32#4]
When create an ermrest row, if the row already exists, it will give a 509 back. We should be able to specify on_conflict, whether to ignore, throw an error, or update the entry.

**Comment by svoinea** [comment]
Done through the commit 6aa6f762f2da3bcf08c3cc2836f7d34b6562b96a.
The **ermrest** handler should have the **PUT** method with the **colmap** structure specifying the columns row to be created or updated.
It uses the ermrest PUT entity API.

**Comment by karlcz** [comment]
I think we need to be able to configure any ERMrest API and method
from an iobox rule.  We should even have in mind doing a GET to query
for catalog content filtered by metadata and then add result info back
into the iobox rule environment for further processing.

We might be able to have one handler that has parameters to control
the details:
- a template to form the URL or path, including selecting API
- a constant to select the HTTP method
- something to say how any response data goes back to environment

We should probably discuss this soon, before we invest too much in one
implementation approach.  I think the biggest design challenges 
will be:
- any support for conditional processing depending on response status?
- any support for handling multi-row input or output?

But perhaps we can define a simpler core handler that side-steps these
issues for now while having room for future enhancement.
