### ISSUE TITLE
provide a checksum handler for hatrac version of md5 (i.e. hatrac_md5)

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/iobox-win32#5]
The use case is to calculate this checksum like hatrac and save it in catalog.

**Comment by svoinea** [comment]
Implemented in the commit d761da6edc514908d408cfd6e1526df52a072082

**Comment by hongsudt** [comment]
Can you please update the documentation with the new handler name? Thanks.

**Comment by svoinea** [comment]
The README file is already updated.
